language: node_js
node_js:
  - "6"
services:
  - mongodb
before_install:
  - npm install --global gulp
  - npm install -g codeclimate-test-reporter
install:
  - npm install
after_success:
  - codeclimate-test-reporter < coverage/lcov.info
notifications:
  slack: financialtimes:F7ol60TlTlcG7ZP0DvAZWan5
addons:
  apt:
    sources:
      - mongodb-3.0.6
    packages:
      - mongodb-org-server
